### ISSUE TITLE
ECU is flagged by VirusTotal

### ISSUE THREAD

**Issue by IAmSomeoneLol** [dxxxxy/EssentialCosmeticsUnlocker#54]
i found a comment on reddit about this mod and decided to give it a try, though I am always sceptical about mods and check them for viruses, so when I went to VirusTotal and uploaded it, there were 2 detections, from Google and Ikarus "Exploit.JAVA.Banload". 
I didn't run the mod for that reason so now I'm wondering if this is like an Issue or true..
![image](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/99344476/8ee3d019-6879-4a56-b68a-c0f7e2119bb5)

**Comment by dxxxxy** [comment]
Why open this kind of issue on Github? There is nothing I can do to solve this. If, with your judgment, you think you should not use this, then do not.

**Comment by IAmSomeoneLol** [comment]
> Why open this kind of issue on Github? There is nothing I can do to solve this. If, with your judgment, you think you should not use this, then do not.

I mean no offense here, but when it comes to Viruses it's a big thing for me personally. I was just wondering if this was a Known thing cause I hadn't seen it mentioned anywhere on the Description.

**Comment by PureFallen** [comment]
Virus Detection this days is moving away from a standalone "I detect a virus by it's signature" approach because there are to many methods into bypassing this. Modern solutions will try for more dynamic scans that will try to evaluate a software through heuristic. Think of it as "when it behaves like known malware, it will probably be malware".

ECU is using Mixins and does things for a modification that are rather unusual for a Minecraft Modification. It does share a lot of things with malware in this regards which makes it so that a handful of false detections through Antivirus software is to be expected. Definitely not worthy a Github issue however. Not a lot the developer can do other than trying to add evasion methods that in itself might as well trigger differently antivirus heuristic detections. A game of Whack-A-Mole that would go on forever.

**Comment by nscwb** [comment]
I can confirm it is safe to use. Enjoy.
